package com.kblack.offlinemap.ui.theme

import androidx.compose.ui.graphics.Color

/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * "Cartography Teal" — the v2 reskin color system, seeded from #0B4F45.
 *
 * Two independent palettes, not one derived from the other:
 *  - Light: standard M3 surface roles on a warm off-white ground (#F7F5EC), for daytime /
 *    outdoor use. The outdoor-legibility floor for this app is 4.5:1 for any text and 3:1 for
 *    any icon or control edge, checked against each token's paired on-color — do not add a
 *    pair below that floor.
 *  - Amoled: background is a *real* #000000 so unlit OLED pixels stay off at night, not a "dim
 *    of light" the way a conventional Material dark theme reads (a raised dark grey base).
 *    #101614 is the first raised container, never the background.
 *
 * Values are hand-authored to match the design spec (Offline Map M3 Expressive Spec, sheets 1a
 * and 1b) rather than generated by the M3 theme builder from a single seed — re-check contrast
 * against the spec before regenerating any of this.
 *
 * ## Every role in ColorScheme has a value here, on purpose
 *
 * Material 3's ColorScheme has 48 roles. An earlier revision of this file defined roughly half
 * and aliased or omitted the rest. That is not a saving: a stock M3 component *will* ask for
 * `tertiaryContainer` or `inverseSurface` eventually, and a role left to the library default
 * answers with Baseline purple in the middle of a teal app. Roles this app does not use in its
 * own screens are still given an in-palette value, and are marked "unused by app UI" so the
 * distinction between "not used" and "not defined" stays visible.
 */

// ---------------------------------------------------------------------------------------------
// Light
// ---------------------------------------------------------------------------------------------

val primaryLight = Color(0xFF0B4F45)
val onPrimaryLight = Color(0xFFFFFFFF) // 9.6:1 on primary
val primaryContainerLight = Color(0xFFCFE8DE)
val onPrimaryContainerLight = Color(0xFF05302A) // 11.4:1 on primaryContainer

val secondaryLight = Color(0xFF3C6659)
val onSecondaryLight = Color(0xFFFFFFFF) // 6.1:1 on secondary
val secondaryContainerLight = Color(0xFFD6E8DF)
val onSecondaryContainerLight = Color(0xFF20342D) // 12.1:1 on secondaryContainer

/*
 * Tertiary is a real M3 role and is deliberately UNUSED BY APP UI. It exists so that a stock
 * component asking for it gets an in-palette answer instead of the Baseline purple.
 *
 * It used to alias secondary here. That was worse than it looked: a component that asks for
 * tertiary specifically to differentiate itself from secondary would have rendered identically
 * to secondary, i.e. the alias silently defeated the component's own design. The spec gives it
 * a real cool-blue value for exactly that reason.
 */
val tertiaryLight = Color(0xFF3B5F72)
val onTertiaryLight = Color(0xFFFFFFFF) // 6.6:1 on tertiary
val tertiaryContainerLight = Color(0xFFCDE6F5)
val onTertiaryContainerLight = Color(0xFF1B3745) // 11.2:1 on tertiaryContainer

val errorLight = Color(0xFF8A2E2E) // routing failure
val onErrorLight = Color(0xFFFFFFFF) // 7.4:1 on error
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002) // 13.9:1 on errorContainer

val backgroundLight = Color(0xFFF7F5EC)
val onBackgroundLight = Color(0xFF171D1A) // 15.6:1 on background
val surfaceLight = Color(0xFFF7F5EC)
val onSurfaceLight = Color(0xFF171D1A) // 15.6:1 on surface
val surfaceVariantLight = Color(0xFFE1E5DC)
val onSurfaceVariantLight = Color(0xFF414942) // 8.4:1 on surfaceVariant

val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF2F0E6)
val surfaceContainerLight = Color(0xFFECEAE0)
val surfaceContainerHighLight = Color(0xFFE6E4DA)
val surfaceContainerHighestLight = Color(0xFFE1E5DC)

val inverseSurfaceLight = Color(0xFF2C322E) // snackbar ground
val inverseOnSurfaceLight = Color(0xFFEEF2EC) // 12.6:1 on inverseSurface
val inversePrimaryLight = Color(0xFF7FD7C1)
val outlineLight = Color(0xFF71796F)
val outlineVariantLight = Color(0xFFC1C8BE)
val surfaceDimLight = Color(0xFFD9D7CE)
val surfaceBrightLight = Color(0xFFFFFFFF)
val surfaceTintLight = primaryLight // M3 defines surfaceTint as primary; stated rather than implied
val scrimLight = Color(0xFF000000) // scrim @ 32% is applied at the paint, not baked in here

/** Sharp-turn / caution warning role. Not a standard M3 ColorScheme slot — see CustomColors. */
val warningLight = Color(0xFFB4711F) // fill/icon-only — 3.4:1, not for body text
val onWarningLight = Color(0xFFFFFFFF)
val warningContainerLight = Color(0xFFFFDDB0)
val onWarningContainerLight = Color(0xFF3A2100) // 11.8:1 on warningContainer

// ---------------------------------------------------------------------------------------------
// Amoled (true black — see file header; NOT a darkColorScheme derived from Light)
// ---------------------------------------------------------------------------------------------

val primaryAmoled = Color(0xFF7FD7C1)
val onPrimaryAmoled = Color(0xFF003830) // 9.9:1 on primary
val primaryContainerAmoled = Color(0xFF005046)
val onPrimaryContainerAmoled = Color(0xFF9CF3DC) // 7.1:1 on primaryContainer

val secondaryAmoled = Color(0xFF9CC9BA)
val onSecondaryAmoled = Color(0xFF0B3229)
val secondaryContainerAmoled = Color(0xFF20342D)
val onSecondaryContainerAmoled = Color(0xFFD6E8DF)

/** Unused by app UI — see the note on [tertiaryLight]. Cool-blue counterpart for AMOLED. */
val tertiaryAmoled = Color(0xFF9BCDE4)
val onTertiaryAmoled = Color(0xFF12333F) // 9.4:1 on tertiary
val tertiaryContainerAmoled = Color(0xFF24485A)
val onTertiaryContainerAmoled = Color(0xFFCDE6F5) // 7.8:1 on tertiaryContainer

val errorAmoled = Color(0xFFFFB4AB)
val onErrorAmoled = Color(0xFF5C0004) // 8.3:1 on error
val errorContainerAmoled = Color(0xFF93000A)
val onErrorContainerAmoled = Color(0xFFFFDAD6) // 5.51:1 on errorContainer

val backgroundAmoled = Color(0xFF000000)
val onBackgroundAmoled = Color(0xFFE6EBE6) // 17:1 on background
val surfaceAmoled = Color(0xFF080B0A)
val onSurfaceAmoled = Color(0xFFE6EBE6) // 17:1 on surface
val surfaceVariantAmoled = Color(0xFF202A26)
val onSurfaceVariantAmoled = Color(0xFFC1C8BE)

val surfaceContainerLowestAmoled = Color(0xFF000000)

/**
 * Spec 1b names surface / container / High / Highest but not Low. This value sits between
 * [surfaceAmoled] and [surfaceContainerAmoled] so the five-step ladder the AMOLED elevation
 * model depends on (see [Elevation]) has no gap in it. Flagged so nobody reads it as spec'd.
 */
val surfaceContainerLowAmoled = Color(0xFF0B0F0E)
val surfaceContainerAmoled = Color(0xFF101614)
val surfaceContainerHighAmoled = Color(0xFF18201D)
val surfaceContainerHighestAmoled = Color(0xFF202A26)

val inverseSurfaceAmoled = Color(0xFFE6EBE6) // snackbar ground
val inverseOnSurfaceAmoled = Color(0xFF2C322E) // 12.9:1 on inverseSurface
val inversePrimaryAmoled = Color(0xFF0B4F45)
val outlineAmoled = Color(0xFF8A938A)
val outlineVariantAmoled = Color(0xFF3A423D)
val surfaceDimAmoled = Color(0xFF000000)
val surfaceBrightAmoled = Color(0xFF3A423E)
val surfaceTintAmoled = primaryAmoled
val scrimAmoled = Color(0xFF000000)

/**
 * One value per role. #452B00 previously appeared alongside #432C00 for this exact role across
 * three screens — two hex values for one meaning, which is how a theme ends up impossible to
 * retune. #432C00 is the spec'd value; #452B00 is gone.
 */
val warningAmoled = Color(0xFFF2B65C)
val onWarningAmoled = Color(0xFF432C00) // 8.8:1 on warning
val warningContainerAmoled = Color(0xFF432C00)
val onWarningContainerAmoled = Color(0xFFF2B65C)

// ---------------------------------------------------------------------------------------------
// The twelve Fixed roles — same value in light and AMOLED, by contract
// ---------------------------------------------------------------------------------------------

/*
 * primaryFixed / primaryFixedDim / onPrimaryFixed / onPrimaryFixedVariant, and the same four
 * each for secondary and tertiary.
 *
 * These exist so a surface can hold the SAME colour in light and dark — a split pane or a
 * side-by-side layout where one half must not flip with the theme. This app has no such surface:
 * every screen is single-scheme and the AMOLED variant is a deliberate full flip, so these are
 * UNUSED BY APP UI.
 *
 * They are populated rather than left to the library because that is what the Fixed contract
 * means: each resolves to its LIGHT-scheme counterpart in both themes, so a stock component that
 * asks for one renders correctly and legibly — it simply never appears in this app's own screens.
 *
 * The spec gives primaryFixedDim (#A8CFC3) as the worked example. The secondary and tertiary Dim
 * values below are derived by applying that same per-channel ratio to their own containers
 * (R x0.81, G x0.89, B x0.88), so they are traceable to a stated decision rather than picked by
 * eye. If the spec ever names them explicitly, replace these and delete this paragraph.
 */

val primaryFixed = primaryContainerLight // #CFE8DE
val primaryFixedDim = Color(0xFFA8CFC3)
val onPrimaryFixed = onPrimaryContainerLight // #05302A
val onPrimaryFixedVariant = primaryLight // #0B4F45

val secondaryFixed = secondaryContainerLight // #D6E8DF
val secondaryFixedDim = Color(0xFFADCFC4) // derived — see note above
val onSecondaryFixed = onSecondaryContainerLight // #20342D
val onSecondaryFixedVariant = secondaryLight // #3C6659

val tertiaryFixed = tertiaryContainerLight // #CDE6F5
val tertiaryFixedDim = Color(0xFFA6CDD7) // derived — see note above
val onTertiaryFixed = onTertiaryContainerLight // #1B3745
val onTertiaryFixedVariant = tertiaryLight // #3B5F72

// ---------------------------------------------------------------------------------------------
// App-specific surfaces that are not M3 roles
// ---------------------------------------------------------------------------------------------

/*
 * Each of these was already painting pixels across the design boards with no name, which is the
 * precise condition under which a colour gets hardcoded at implementation time and then drifts.
 * They are carried in CustomColors, never in ColorScheme, so a custom token can never be
 * mistaken for a stock one.
 */

/** The map canvas ground beneath the MapLibre style. 12.1:1 against [onSurfaceLight]. */
val mapSurfaceLight = Color(0xFFE4E7DE)

/**
 * AMOLED has no spec'd map ground: at night the MapLibre style paints its own dark canvas edge
 * to edge, so the app surface below it is only ever seen for a frame during style load. Matching
 * [surfaceAmoled] keeps that frame black rather than flashing a light rectangle.
 */
val mapSurfaceAmoled = surfaceAmoled

/** Ground under the floating nav pill / bottom bar. 8.9:1 against [onNavSurfaceLight]. */
val navSurfaceLight = Color(0xFF22302B)
val onNavSurfaceLight = Color(0xFFCFE8DE)

/** Hairline border on [navSurfaceLight]. 1.5:1 to its own container — decorative only. */
val outlineVariantOnNavLight = Color(0xFF3A4A44)

val navSurfaceAmoled = Color(0xFF18201D)
val onNavSurfaceAmoled = Color(0xFFBFC9C0) // 8.1:1 on navSurface
val outlineVariantOnNavAmoled = Color(0xFF3A423D)

// ---------------------------------------------------------------------------------------------
// Fixed tokens — same value in every scheme (light and Amoled), on purpose.
//
// "Personalization ceiling" from the spec: a user-chosen accent may retint map controls, the
// FAB, the route line, settings accents and list selection — but it must NEVER retint the
// active-navigation turn card, the HUD numerals, the sharp-turn amber, or the End-navigation
// button. Those four are locked to fixed pairs so every color scheme keeps >=4.5:1 in direct
// sunlight, independent of theme or dynamic color. Do not source these from the ColorScheme.
//
// Not to be confused with the twelve M3 *Fixed roles* above: those are a Material contract about
// light/dark parity. These are an app rule about which surfaces dynamic colour may not touch.
// ---------------------------------------------------------------------------------------------

val turnCardFixed = Color(0xFF0B4F45)
val onTurnCardFixed = Color(0xFFFFFFFF)
val hudNumeralFixed = Color(0xFFFFFFFF)
val sharpTurnAmberFixed = Color(0xFFB4711F)
val onSharpTurnAmberFixed = Color(0xFFFFFFFF)
val endNavigationFixed = Color(0xFF8A2E2E)
val onEndNavigationFixed = Color(0xFFFFFFFF)
